backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/main.md"
        name: "main"
        label: "Main Page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Background_Image, name: backgroundImage, widget: image}, {label: Heading, name: heading, widget: string}, {label: Items, name: items, widget: list, fields: [{label: Text, name: text, widget: text}]}]}
          - {label: About, name: about, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Text, name: text, widget: markdown}, {label: Image, name: image, widget: image}]}
          - {label: Skills, name: skills, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Items, name: items, widget: list, fields: [{label: Text, name: text, widget: text}]}, {label: Image, name: image, widget: image}]}
          - {label: Clients, name: clients, widget: object, fields: [{label: Background_Image, name: backgroundImage, widget: image}, {label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list, fields: [{label: Text, name: text, widget: text}]}]}
          - {label: Contact_Bottom, name: contactBottom, widget: object, fields: [{label: Heading, name: heading, widget: string}]}